### ISSUE TITLE
Examples for "bad practices"

### ISSUE THREAD

**Issue by bast** [coderefinery/documentation#113]
@Sabryr started this lesson with examples for "bad" practices from own projects. This was super useful but it's not part of the material. Perhaps we can collect own examples in the material?

**Comment by bast** [comment]
Lucy:
> You could put up the web addresses for the two documentation examples and give people 5 minutes to discuss what they like / don't like about each before discussing it as a class.

**Comment by bast** [comment]
It would be nice to get examples from the entire team so that we don't have to show "bad" examples from somebody outside the team. I can certainly come up with few bad examples of mine but would really appreciate examples.

**Comment by rkdarst** [comment]
I guess we shouldn't call these "bad" examples, since all examples will have some good things and some bad things about them (the only "bad" one would have nothing, thus nothing to discuss).  To phrase it more nicely, we could say "different levels of maturity of documentation"

* One example from my colleague: https://github.com/CxAalto/gtfspy (maturity level: has README, links to examples, still hard to get started though.  Otherwise set up well.)
* One of my own projects: https://github.com/CxAalto/niimpy/ (maturity level: has README and two .ipynb files as manuals, but there aren't good tutorials and isn't a good reference to see what is available... it's somewhat unstructured prose.  If you follow the link to the wiki, you get a badly structured wiki which is an example of bad docs, too.)

I'm not sure if these are the best examples to use, but I offer them as starting points.

**Comment by rkdarst** [comment]
* Here's an example of mine that is actually bad (and unlike the others, will probably stay bad because this isn't in active use anymore): https://github.com/rkdarst/pcd.  No docs at all, but note a `doc/` directory which *tries* to do something, but incomplete and not available anywhere.  This could also be used as an example of missing README, LICENSE, Github description, Github homepage link, etc - all of which are important to usability.  So this gives a lot to talk about.  I give permission to use this as an example.

**Comment by bast** [comment]
I agree about the naming: it will not be called "bad". I will call it something like "own examples" which we take as starting point for discussion.

**Comment by bast** [comment]
@Sabryr you had some good examples. Do you mind if we link to them from the material?
