### ISSUE TITLE
Change focus of lesson to in-code documentation and README files

### ISSUE THREAD

**Issue by svenvanderburg** [coderefinery/documentation#166]
We [netherlands escience center](https://www.esciencecenter.nl/) have taught the documentation lesson in a coderefinery workshop twice. This repository was of great value for that so the development effort is highly appreciated! 

Both times we received the same feedback from students that although they liked learning about sphinx and readthedocs, for most of their PhD-ware projects having such an extensive documentation is overkill. Instead they want to learn stuff that is more applicable to their daily work. We decided to reshape the entire lesson to teach more about in-code documentation, what should go into a README file, and with only a short demo of sphinx + readthedocs. This turned out to be a succes and I hereby share the lesson that we taught.

Some links:
* ['Our' documentation lesson in github](https://github.com/escience-academy/coderefinery-documentation)
* I've create a draft PR with a description of the changes: #165 .
* See ['our' lesson webpage](https://escience-academy.github.io/coderefinery-documentation/).

I am curious to hear what you think of it, I can see mostly 3 options to proceed with this further:
1. We use 'our' version as the official coderefinery lesson, but with the sphinx and readthedocs episodes as optional episodes.
2. We add the in-code documentation and README episodes as optional lessons
3. We keep things separate and make a mental note that this alternative content exists.

I am willing to pick up further improving #165 based on your thoughts.

**Comment by bast** [comment]
Sorry I missed this issue before commenting on the PR so let's perhaps talk here.

I agree that in-code documentation and README is good enough for many/most smaller project and the whole RTD machinery might be too heavy and I like this focus.

My recommendation is that we merge in your two new episodes and we make this more modular and offer to future instructors (and also learners) the possibility to pick modules and teach a subset but to offer the rest also for reading. In other words I would prefer that we combine efforts and make this more modular rather than forking efforts (but of course forking is also completely fine).

At this time, @samumantha and me are working on moving the lesson to Sphinx which has a couple of advantages. The main advantage in this context is that it will make browsing easier - I believe - and also make this mixing and matching easier.

One disadvantage is that it will make everything in #165 conflict :-) But my suggestion is that we finish the port to Sphinx this week, there is not very much left, and after that I help you getting your two lessons in (let's try it then in smaller PRs) and also help with the instructor meta-text to offer different routes to present the material. Does that sound good?

**Comment by bast** [comment]
Other motivations for moving to Sphinx:
- eating own medicine
- easier local preview
- we can have tabs and avoid code duplication
- literalinclude
- better code highlighting options

**Comment by svenvanderburg** [comment]
@bast OK, the modular approach sounds good! 

After #167 if you like I will add these 2 new episodes and update the instructor instructions and landing page accordingly. Or let me know if you want to take the lead here.

I foresee 3 PRs:
1. in-code documentation lesson
2. Readme lesson 
3. Updated instructor notes and index.md

For the Readme lesson you should fork https://github.com/escience-academy/coderefinery-documentation-example-project to the coderefinery organisation.

It will not be exactly modular, since the Readme lesson depends on the in-code documentation lesson. But the same is true for the readhtedocs episode depending on the sphinx episode.

I think the sphinx+readthedocs demo episode is powerful in case you just want to demo that instead of teaching the full thing, but I think it becomes a bit confusing to put the episode in there. Maybe we can point to https://github.com/escience-academy/coderefinery-documentation-example-project and it's corresponding readthedocs page in the instructor notes and mention they can use that as a demo instead of the sphinx + readthedocs episodes.

**Comment by bast** [comment]
Sounds good (the 3 PRs, us forking the example project). And I think it's OK if some episodes are coupled with other episodes and in instructor notes we can then discuss different possible "routes".

I will let you know once we have a relatively stable base to base the PRs on (might take a couple of days).

**Comment by bast** [comment]
I think the lesson sources are now stable enough for pull requests 1 and 2 (above numbering; I will help with 3 and also happy to help with 1 and 2). Also let me know if I should recreate PRs 1 and 2 from the closed big PR.

**Comment by svenvanderburg** [comment]
I just submitted #179 and #180 for the two episodes, they can be reviewed. I hope to add a 3rd PR updating instructor notes soon.

**Comment by bast** [comment]
Thank you! Reviewing ...

**Comment by svenvanderburg** [comment]
And #182 to update the instructions! :)

**Comment by bast** [comment]
Thanks again for these great changes! I will do some small adjustments to these lessons but these are great additions.

**Comment by svenvanderburg** [comment]
Cool. It feels good to contribute, thanks for the pro-active guidance! ❤️
