### ISSUE TITLE
Show how to render (LaTeX) math equations

### ISSUE THREAD

**Issue by bast** [coderefinery/documentation#82]
As an example. This was asked already a couple of times.

**Comment by rkdarst** [comment]
> As an example. This was asked already a couple of times.

Surprisingly just this morning homeone here had a panic getting it to
work.  It turns out we were using it wrong, so here it is.

```
..math::

	displaymath

:math:`inline math`
```

Then add sphinx.ext.mathjax to the list of extensions.  It doesn't
Just Work if you do the "native" mathjax way of putting it in $$ $$ or
\[ \] yourself... because then that would only work in the HTML
renderer.

... we haven't tested the above, but we *did* test the wrong way so we
had to figure this out...
